version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    container_name: presisso-db
    environment:
      POSTGRES_USER: presisso
      POSTGRES_PASSWORD: presisso_dev
      POSTGRES_DB: presisso_studio
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U presisso']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
